# Generated by Django 5.0.1 on 2024-02-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_com1', '0003_alter_form1_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myfileupload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=50)),
                ('my_file', models.FileField(upload_to='')),
            ],
        ),
    ]
