# Generated by Django 5.0.1 on 2024-02-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_com1', '0005_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, choices=[('fruit', 'Fruit'), ('vegetable', 'Vegetable'), ('meat', 'Meat'), ('bread', 'Bread')], max_length=10, null=True),
        ),
    ]
