# Generated by Django 5.0.1 on 2024-02-24 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_com1', '0007_alter_product_product_type_delete_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='form1',
        ),
        migrations.DeleteModel(
            name='Myfileupload',
        ),
    ]
